from tkinter import*
form=Tk()
form.geometry("700x500")

lbl1=Label(form,text="label 1",font =("None 25 bold"))
lbl1.grid(row =0,column=0)
lbl2=Label(form,text="label 2",font =("None 25 bold"))
lbl2.grid(row =1,column=1)

btn1 =Button(form ,text ="clich here",font =("None 25 bold"))
btn1.grid(row=0,column=1)
btn2 =Button(form ,text ="click here",font =("None 25 bold"))
btn2.grid(row=1,column=2)
frame =Frame(form)
frame.grid(row =2,column =0,columnspan=3)
lbl3=Label(frame,text="label 3",font =("None 25 bold"))
lbl4=Label(frame,text="label 4",font =("None 25 bold"))
lbl5=Label(frame,text="label 5",font =("None 25 bold"))
lbl6=Label(frame,text="label 6",font =("None 25 bold"))
lbl7=Label(frame,text="label 7",font =("None 25 bold"))
lbl3.grid(row =0,column=0)
lbl4.grid(row =0,column=1)
lbl5.grid(row =0,column=2)
lbl6.grid(row =0,column=3)
lbl7.grid(row =0,column=4)
